# Site wide configuration

title: Fear, Racism & Zombies
description: "About Zombies"
logo: bio-photo.jpg
teaser: bio-photo.jpg
locale: en
url: http://localhost:4000

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Nabil Kashyap
  web: http://digitalscholarship.swarthmore.edu
  email: digitalscholarship@swarthmor.edu
  twitter: _nabilk

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
